# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-21 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=15, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=100, verbose_name='Rua')),
                ('id_aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Aluno')),
            ],
        ),
    ]
