# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-21 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='id_aluno',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Aluno'),
        ),
    ]
